### ISSUE TITLE
Recipe book hints still show up

### ISSUE THREAD

**Issue by amhurg** [Grayray75/NoRecipeBook#2]
![this still shows up](https://user-images.githubusercontent.com/112481375/188617249-67d0bb60-e332-4a60-aa51-ae5598b9aef8.png)
yep.

**Comment by Grayray75** [comment]
Thanks for reporting this issue.
Unfortunately, I am very busy at the moment and don't have time to work on my mods.
But I will fix the problem as soon as I have time again.

**Comment by Grayray75** [comment]
I just fixed this issue and will release a new version soon.
