### ISSUE TITLE
Recipe toasts still appear

### ISSUE THREAD

**Issue by TheStaticVoid** [Grayray75/NoRecipeBook#3]
This was marked as fixed in #2, however in a fresh instance with only this mod it still appears.
- Fabric 0.14.22
- NoRecipeBook 2.2+1.19

**Comment by Grayray75** [comment]
You are using an old version it seems.
Recipe toasts were disabled in v2.3

**Comment by TheStaticVoid** [comment]
![image](https://github.com/Grayray75/NoRecipeBook/assets/6089108/ce4e860c-eda0-4a74-88af-2d68da195dd3)

This is the only version that is available for 1.19.2

**Comment by Grayray75** [comment]
I forgot to set the Minecraft version correctly on Curseforge.
Just download v2.3 it also works with Minecraft 1.19.2

**Comment by TheStaticVoid** [comment]
I see you marked 2.3 for 1.19.2 and everything seems to be working good now
